### ISSUE TITLE
CSVs other than Mft and MftExtra don't use specified delimiter in headers

### ISSUE THREAD

**Issue by grv87** [jschicht/Mft2Csv#10]
For example, `Mft-LOGGED_UTILITY_STREAM_2022-07-25_00-43-58.csv`:

```
MftRef|MftRefSeqNo|StreamName|StreamSize
5;5;$TXF_DATA;56
31;31;$TXF_DATA;56
```

I specified `;` as delimiter, and it was used in the data rows. But not in the header.

**Comment by jschicht** [comment]
This issue should be solved in v45.
