### ISSUE TITLE
autoit error

### ISSUE THREAD

**Issue by Volguy** [jschicht/Mft2Csv#2]
while running the mft2csv (64 and 32 bit versiosn) on a live partition i encounterd the following autoit error:
"Array variable has incorrect number of subscripts or subscript dimension range exceeded"
any suggestions ?@jschicht

**Comment by jschicht** [comment]
If you could send me the log file it may give me some clues. If you also have some more details about the volume and OS, please send it along to joakim.schicht@gmail.com.  And what version of mft2csv are you running?

**Comment by jschicht** [comment]
If this problem exist in latest version, please open a new issue.
