### ISSUE TITLE
Unable to run Mft2Csv

### ISSUE THREAD

**Issue by ashleykellyforensics** [jschicht/Mft2Csv#7]
I've downloaded Mft2Csv to two Win10 machines.  I can open the executable but when I click on Start Processing the GUI goes away, a folder is created, but no MFT is parsed.  I've tried parsing my MFT on the C drive as well as E01 images.

**Comment by SadFool** [comment]
I'd recommend having a look in the log file, which is in the output path. I had the exact same issue - after checking the log I realized you'll have to untick 'dump everything' if you want to create a log2timeline output.

**Comment by jschicht** [comment]
The log should indicate what may be the problem. The new gui is hopefully more intuitive.

**Comment by mirh** [comment]
OP was talking about about an outright crash, not just null results. 
And AFAICT that happens when you run the program without administrator privilege. 
https://github.com/jschicht/Mft2Csv/blob/0c95e94b18adc83baa8699db55689c87986780aa/Mft2Csv.au3#L1
For some twisted reason, that's commented out.
